(function (global) {
  'use strict';

  const RESOURCES = {
    'res-projector': {
      title: 'HD Projector',
      image: 'https://images.unsplash.com/photo-1505373877841-8d25f7d46678?w=900&h=600&fit=crop&crop=center',
      images: [
        'https://images.unsplash.com/photo-1505373877841-8d25f7d46678?w=900&h=600&fit=crop',
        'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=900&h=600&fit=crop',
        'https://images.unsplash.com/photo-1573164713714-d95e436ab8d6?w=900&h=600&fit=crop',
      ],
      imageAlt: 'HD Projector',
      category: 'Equipment',
      badge: 'Available',
      badgeClass: 'badge-available',
      quantity: '1 unit',
      condition: 'Good',
      location: 'IT Society Cabinet',
      availability: 'Jun 1 – Aug 31, 2026',
      availCount: '1 available',
      borrowedCount: null,
      from: 'IT Society',
      fromImg: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=96&h=96&fit=crop',
      tagline: 'Portable HD projector for seminars, film screenings, and campus presentations.',
      description: 'Portable HD projector suitable for seminars, film screenings, and community presentations. Includes remote control and carrying case. Borrowers must return within agreed dates and report any damage.',
      guidelines: [
        'Submit a request at least 3 days before needed date.',
        'Valid organization or student ID required.',
        'Return on or before the agreed return date.',
        'Responsible for repair costs if damaged while borrowed.',
      ],
      orgType: 'Student Organization',
      postedAt: '5 days ago',
      responseTime: 'Usually within 24 hours',
    },
    'res-sound': {
      title: 'Sound System',
      image: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=900&h=600&fit=crop',
      images: [
        'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=900&h=600&fit=crop',
        'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=900&h=600&fit=crop',
      ],
      imageAlt: 'Sound system',
      category: 'Equipment',
      badge: 'Available',
      badgeClass: 'badge-available',
      quantity: '1 set',
      condition: 'Good',
      location: 'Music Room',
      availability: 'Jun 1 – Aug 31, 2026',
      availCount: '1 available',
      borrowedCount: null,
      from: 'Music Society',
      fromImg: 'https://i.pravatar.cc/96?img=20',
      tagline: 'Full sound system with two speakers, amplifier, and microphone set.',
      description: 'Full sound system with two speakers, amplifier, and microphone set. Ideal for outdoor events, concerts, and campus activities.',
      guidelines: [
        'Request at least 5 days in advance for large events.',
        'Borrower must be present during setup.',
        'Return all components including cables.',
        'Damage deposit may be required.',
      ],
      orgType: 'Student Organization',
      postedAt: '1 week ago',
      responseTime: 'Usually within 48 hours',
    },
    'res-tables': {
      title: 'Folding Tables (set of 5)',
      image: 'https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?w=900&h=600&fit=crop',
      images: [
        'https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?w=900&h=600&fit=crop',
      ],
      imageAlt: 'Folding tables',
      category: 'Furniture',
      badge: 'Reserved',
      badgeClass: 'badge-reserved',
      quantity: '5 tables',
      condition: 'Fair',
      location: 'Events Room',
      availability: 'Year-round',
      availCount: 'Currently reserved',
      borrowedCount: null,
      from: 'Events Committee',
      fromImg: 'https://i.pravatar.cc/96?img=30',
      tagline: 'Set of 5 lightweight folding tables for booths, bazaars, and community events.',
      description: 'Set of 5 lightweight folding tables suitable for booths, bazaars, and community events. Easy to transport and set up.',
      guidelines: [
        'Book at least 2 days before the event.',
        'Tables must be returned clean and dry.',
        'Do not drag tables on rough surfaces.',
        'Stack properly when returning.',
      ],
      orgType: 'Student Committee',
      postedAt: '2 weeks ago',
      responseTime: 'Usually within 24 hours',
    },
    'res-chairs': {
      title: 'Plastic Chair',
      image: 'https://i.pinimg.com/1200x/bb/2e/9d/bb2e9d35c8597ad3b2d1b91aaed6376d.jpg',
      images: [
        'https://i.pinimg.com/1200x/bb/2e/9d/bb2e9d35c8597ad3b2d1b91aaed6376d.jpg',
        'https://images.unsplash.com/photo-1567016432779-094069958ea5?w=900&h=600&fit=crop',
        'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=900&h=600&fit=crop',
        'https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?w=900&h=600&fit=crop',
        'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=900&h=600&fit=crop',
      ],
      imageAlt: 'Plastic chairs arranged in rows',
      category: 'Furniture',
      badge: 'Available',
      badgeClass: 'badge-available',
      quantity: '25 pieces',
      condition: 'Good',
      location: 'NSTP Office Storage',
      availability: 'Quezon City, Philippines',
      availCount: '1 available',
      borrowedCount: '24 already borrowed',
      from: 'NSTP Office',
      fromImg: null,
      tagline: 'Durable plastic chairs suitable for events, seminars, trainings, and community activities.',
      description: 'Lightweight yet sturdy plastic chairs for various indoor and outdoor events. Easy to stack and clean.',
      guidelines: [
        'Handle with care and return in good condition.',
        'Return on or before the agreed date.',
        'Late returns may affect future borrow requests.',
      ],
      orgType: 'University Office',
      postedAt: '3 days ago',
      responseTime: 'Usually within 24 hours',
    },
    'res-art': {
      title: 'Art Materials Kit',
      image: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=900&h=600&fit=crop',
      images: [
        'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=900&h=600&fit=crop',
      ],
      imageAlt: 'Art materials',
      category: 'Supplies',
      badge: 'Available',
      badgeClass: 'badge-available',
      quantity: '1 kit',
      condition: 'New',
      location: 'Marketing Club Room',
      availability: 'Jun – Jul 2026',
      availCount: '1 available',
      borrowedCount: null,
      from: 'Marketing Club',
      fromImg: 'https://i.pravatar.cc/96?img=50',
      tagline: 'Complete art kit including acrylic paints, assorted brushes, canvas paper, and palette.',
      description: 'Complete art kit including acrylic paints, assorted brushes, canvas paper, and palette. Suitable for workshops, murals, and community art projects.',
      guidelines: [
        'Available for organization-led activities only.',
        'Return unused materials in original packaging.',
        'Brushes must be cleaned before return.',
        'Consumables (paint, paper) are not refunded.',
      ],
      orgType: 'Student Organization',
      postedAt: '4 days ago',
      responseTime: 'Usually within 24 hours',
    },
    'res-cleaning': {
      title: 'Cleaning Materials',
      image: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=900&h=600&fit=crop',
      images: [
        'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=900&h=600&fit=crop',
      ],
      imageAlt: 'Cleaning supplies',
      category: 'Supplies',
      badge: 'Available',
      badgeClass: 'badge-available',
      quantity: '1 kit',
      condition: 'Good',
      location: 'Eco Warriors Locker',
      availability: 'Year-round',
      availCount: '1 available',
      borrowedCount: null,
      from: 'Eco Warriors',
      fromImg: 'https://i.pinimg.com/1200x/3e/45/e4/3e45e4ce0f35e9471fc50d6249f8eb85.jpg',
      tagline: 'Cleaning kit for environmental drives and community clean-up events.',
      description: 'Cleaning kit for environmental drives and community clean-up events. Includes heavy-duty gloves, trash bags, tongs, and sorting containers.',
      guidelines: [
        'Available for registered clean-up events only.',
        'Return all reusable items after the activity.',
        'Consumables (bags, gloves) are provided as needed.',
        'Coordinate with Eco Warriors at least 2 days before.',
      ],
      orgType: 'Student Organization',
      postedAt: '1 week ago',
      responseTime: 'Usually within 24 hours',
    },
  };

  function detailUrl(id) {
    return `resource-detail.html?id=${encodeURIComponent(id)}`;
  }

  function getResource(id) {
    return RESOURCES[id] || null;
  }

  global.UnityHubResources = {
    RESOURCES,
    detailUrl,
    getResource,
    defaultId: 'res-chairs',
  };
})(typeof window !== 'undefined' ? window : globalThis);